### ISSUE TITLE
Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by sandbreak80** [Appdynamics/CWOM-Action-Integration#18]
Hi there. Just tried to setup IWO branch. When opening node with the IWO app ID there is an error. Please advise. Thanks. Brad / AppD

{
  method: 'GET',
  url: 'https://intersight.com/wo/api/v3/supplychains?uuids=74359685456075&detail_type=entity&health=true',
  body: '',
  headers: {
    Accept: 'application/json',
    Host: 'intersight.com',
    Date: 'Wed, 30 Mar 2022 19:21:25 GMT',
    Digest: 'SHA-256=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
    Authorization: 'Signature keyId="620e9eba7564612d33c6c0dc/62153b9a7564612d32c3bac9/624496ff7564612d323c0463\n' +
      '",algorithm="rsa-sha256",headers="(request-target) date digest host",signature="ad0bUvrXvh43f8CH7Lh8iTGPFPSxU0wAOb22aBNexGNhjGxCMWJ7lcA321rhd98rB0xsvcpAg+8+MlVIqTuzPsVYf+Lk37nm97Uo0z3e6DHgm0G65BdK56tECt7uM5DiRQgrd/fugrrA/zfoBVMJL3K6/hwduoxSzmuWFz9b5VTRlAu6wjSux9ZRp73FphmeB4xuFRVOdoZ99TJGU7BLrXNU0FWr9HlthNJT2InNZ0IyVFUdj4Fguo4kRN/ewxYth1WEcKACmQEbXOrC4QIRaBk7Mi7ERFQ6ZjZ5OTzo2qZRw5vxbWUsi7JMEDgQEiczR8EMc+jI5l6hm4Wafffvzg=="',
    'Content-type': 'application/json'
  },
  resolveWithFullResponse: true
}
Unhandled rejection RequestError: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at new RequestError (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request/request.js:185:22)
    at Request.emit (node:events:327:20)
    at Request.start (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request/request.js:753:10)
    at Request.end (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request/request.js:1511:10)
    at end (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request/request.js:564:14)
    at Immediate._onImmediate (/home/ubuntu/fso-lab-devops/applications/iwo-action-integration/node_modules/request/request.js:578:7)
    at processImmediate (node:internal/timers:462:21)

**Comment by sandbreak80** [comment]
Same result in postman using the displayed Authorization header. There are no extra lines in the private and public key files.
